### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by Patbox** [TheLimeGlass/Skacket#1]
![image](https://user-images.githubusercontent.com/39821509/82753122-99a2fa80-9dc3-11ea-8f77-6d39e96f7bea.png)
Skacket: 1.0.3
Skript: 2.4.1
ProtocolLib: 4.5.1-SNAPSHOT-b451

Server: Tuinity 121cca1

I'm not using skacket in any skript.

**Comment by lucasboss45** [comment]
Was able to reproduce on
Skacket 1.0.3a
Skript 2.4.1
ProtocolLib 451
Paper-375

Problem occurs whenever a sign packet occurs

**Comment by TheLimeGlass** [comment]
Fixed in next version

**Comment by Govindass** [comment]
I am having the same problem

**Comment by TheLimeGlass** [comment]
Fixed in latest versions
