### ISSUE TITLE
Docs for Client World Border ?

### ISSUE THREAD

**Issue by Aeris1One** [TheLimeGlass/Skacket#18]
Hi,
There's no documentation on Skript Hub about client world borders, can you tell me how to use them ?

**Comment by TheLimeGlass** [comment]
https://github.com/TheLimeGlass/Skacket/tree/master/src/main/java/me/limeglass/skacket/elements/expressions the classes have the syntaxes at the top of the class

**Comment by TheLimeGlass** [comment]
Start with ExprClientWorldBorder set it to a variable and then use `send client [side] [world] border %clientworldborder% to %players%`
