### ISSUE TITLE
Anvil Gui Issue 

### ISSUE THREAD

**Issue by annemettean** [TheLimeGlass/Skacket#2]
Server Version: spigot 1.13.2
Skacket Version: 1.0.3a

Description:
Anvil Gui is broken on spigot 1.13.2,
This error is coming in the console: https://pastebin.com/D0Y3mVRE
This error is coming ingame: An internal error occurred while attempting to perform this command.

I also have try to run the example on skripthub, but the same error happen.

**Comment by TheLimeGlass** [comment]
Duplicate #1
