### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by BLACK4585** [TheLimeGlass/Skacket#21]
I always get the following error code in the console when I try to open a shield GUI.
![grafik](https://user-images.githubusercontent.com/71935902/110370420-ee122080-804b-11eb-800f-1798ed3eccac.png)

This error code was caused by this test command:
![grafik](https://user-images.githubusercontent.com/71935902/110370667-447f5f00-804c-11eb-8840-1cfea558275a.png)

Regards,
BLACK

**Comment by TheLimeGlass** [comment]
What version is your ProtocolLib? Try the latest 4.6.0

**Comment by BLACK4585** [comment]
I have tried that now. Doesn't help. When loading, I also get this error message:
![grafik](https://user-images.githubusercontent.com/71935902/111270054-abde7580-862f-11eb-9c22-94bd0c73ca31.png)

**Comment by TheLimeGlass** [comment]
That's an error I can work with. I will investigate if it can be reproduced.

**Comment by TheLimeGlass** [comment]
ProtocolLib apparently fixed this issue in 4.7.0-SNAPSHOT but there are other known issues I have reported to the ProtocolLib GitHub.

**Comment by TheLimeGlass** [comment]
#14 duplicate.
