### ISSUE TITLE
Plugin can't enable

### ISSUE THREAD

**Issue by 5mmx** [TheLimeGlass/Skacket#25]
`

[15:50:38] [Server thread/INFO]: [Skacket] Enabling Skacket v1.0.5
--
152 | [15:50:38] [Server thread/ERROR]: Error occurred while enabling Skacket v1.0.5 (Is it up to date?)
153 | java.lang.NoSuchMethodError: com.comphenix.protocol.injector.packet.PacketRegistry.toPacketTypes(Ljava/util/Set;)Ljava/util/Set;
154 | at com.comphenix.protocol.events.ListeningWhitelist.<init>(ListeningWhitelist.java:96) ~[?:?]
155 | at com.comphenix.protocol.events.ListeningWhitelist.<clinit>(ListeningWhitelist.java:41) ~[?:?]
156 | at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:44) ~[?:?]
157 | at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:52) ~[?:?]
158 | at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:104) ~[?:?]
159 | at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:64) ~[?:?]
160 | at me.limeglass.skacket.listeners.PacketListeners$1.<init>(PacketListeners.java:29) ~[?:?]
161 | at me.limeglass.skacket.listeners.PacketListeners.<clinit>(PacketListeners.java:29) ~[?:?]
162 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282]
163 | at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_282]
164 | at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
165 | at me.limeglass.skacket.Skacket.onEnable(Skacket.java:43) ~[?:?]
166 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Paper-567]
167 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[minecraft_server.jar:git-Paper-567]
168 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[minecraft_server.jar:git-Paper-567]
169 | at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[minecraft_server.jar:git-Paper-567]
170 | at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[minecraft_server.jar:git-Paper-567]
171 | at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[minecraft_server.jar:git-Paper-567]
172 | at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[minecraft_server.jar:git-Paper-567]
173 | at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[minecraft_server.jar:git-Paper-567]
174 | at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[minecraft_server.jar:git-Paper-567]
175 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
176 | [15:50:38] [Server thread/INFO]: [Skacket] Disabling Skacket v1.0.5

`
I get this error when I start the server. Using the latest version of protocol lib that at this time is 4.6.0

**Comment by iGalaxyYT** [comment]
Can reproduce using ProtocolLib 4.6.0 on Paper 1.16.5. Switching back to 4.5.1 fixes the issue, but an update to be compatible with 4.6.0 would be great.

**Comment by TheLimeGlass** [comment]
Duplicate #14
