### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DoubleDoubleX** [TheLimeGlass/Skacket#40]
Not an issue, but rather a question, I could not find another way to contact you so sry if it doesn't fit here. Will there be 1.17 and 1.18 (in the fall) support? What could I do to help that?

**Comment by TheLimeGlass** [comment]
It should work fine with 1.17, it's ProtocolLib that is the issue. Currently the packet manager returns null in the latest 1.17 update with the 4.7.0-SNAPSHOT of ProtocolLib. So we're currently waiting on an update.
