### ISSUE TITLE
Anvil GUI error with 1.16.3

### ISSUE THREAD

**Issue by Tai1er** [TheLimeGlass/Skacket#7]
I got this error when I try to open an anvil GUI with 1.16.3 and both stable and lastest protocolLib
This is the error when I try to use the party exemple.
https://pastebin.com/raw/zzgZJKzn

**Comment by TheLimeGlass** [comment]
I believe the library just needs to be updated which Gradle automatically does every build. You can compile the latest code and do a Gradle build or wait until the next update for a fix.

**Comment by TheLimeGlass** [comment]
Updated in latest version
