### ISSUE TITLE
Problem with client-sided glowing

### ISSUE THREAD

**Issue by Martin2000s** [TheLimeGlass/Skacket#71]
Hello,
I have a problem with client-sided glowing.
It says "the script infinitely (or excessively) repeated itself!"
I don't know if it's a bug or if I did something wrong ;x

command /gfdfsg:
executable by: players
trigger:
loop all entities in radius 10 around player:
set client glowing of loop-entity to true for player for 10 seconds

That's my current code. The plugin said the same thing even when I didn't use any loops and tried to give glow just to myself.

With regards,
Martin

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.10
