### ISSUE TITLE
Sign GUI lines not displaying

### ISSUE THREAD

**Issue by eyp57** [TheLimeGlass/Skacket#72]
![image](https://user-images.githubusercontent.com/79930976/166146593-ac91ed8f-d5f3-4f77-bf5a-388e65481bb1.png)
![image](https://user-images.githubusercontent.com/79930976/166146595-b1632ad6-4abd-4075-a545-315c9c1c35a4.png)

**Versions:**
Skript 2.6.1
Skacket 1.0.9
Purpur 1.18.1

**Comment by TheLimeGlass** [comment]
I cannot reproduce the error. Make sure you have the local variable `{_p}` set and that you're not trying to use `player` in the case you used this.
