### ISSUE TITLE
[FR] Glow time

### ISSUE THREAD

**Issue by OverBrave** [TheLimeGlass/Skacket#78]
Can be adding glow time?
Example:

```
on damage:
    attacker is skeleton:
        set client glowing of attacker to true to player for 10 ticks
```

**Comment by TheLimeGlass** [comment]
You can stop it after waiting 10 ticks

**Comment by OverBrave** [comment]
> You can stop it after waiting 10 ticks

Yes I know, but I was just want did in one string.
