### ISSUE TITLE
Sign lines not displaying

### ISSUE THREAD

**Issue by Fusezion** [TheLimeGlass/Skacket#82]
I know there was another issue report (#72) saying the same thing and you responded with you cannot reproduce this error, however, I'm getting the same issue as them and used the example given by you using the command `/sign`

I'm aware that it's an older issue for an older version so I made this issue

----------

```applescript
command /sign:
	trigger:
		set {_test} to "result"
		open sign gui to player with "Enter text", "vvvvvvvvv", "", and "^^^^^^^^^":
			broadcast lines
			broadcast {_test}
```

----------
## Image Proof
![image](https://user-images.githubusercontent.com/81952476/179367359-bfa936fc-18ac-495e-9947-9ab7b419c6fd.png)

----------
## Version Information
![image](https://user-images.githubusercontent.com/81952476/179367405-425de69a-51ac-4674-8e37-4018e2e81a11.png)

Last I remember protocolLib was something this required or atleast before
![image](https://user-images.githubusercontent.com/81952476/179367435-fcfaf4e8-67c2-4b2d-9dc9-2b28a3683280.png)

**Comment by odgtr** [comment]
same issue, wonder when is this gonna get fixed

**Comment by Fusezion** [comment]
closing at this issue is stale and haven't had a response in over a year, in addition you haven't actually seemed to updated this addon in about a year outside of just merging dependabot stuff
