### ISSUE TITLE
Anvil management does not seem to work in 1.19

### ISSUE THREAD

**Issue by scooby906** [TheLimeGlass/Skacket#84]
the anvil management does not seem to work in 1.19, I have an error in the console with this simple code:

`on rightclick:
    open an anvil gui named "&f&lLore editor" to player with player's tool named "Écris ici":
        stop

on anvil gui use:
      set {_lore} to colored event-string
      set lore of tool of event-player to " " and {_lore}`

Error : [https://pastebin.com/wNkJHjrJ](https://pastebin.com/wNkJHjrJ)

**Comment by TheLimeGlass** [comment]
You can try https://github.com/TheLimeGlass/Skacket/actions/runs/2827392727 the nightly-jar builds zip jar and see if that fixes issue

**Comment by TheLimeGlass** [comment]
1.0.12 adds 1.19 support
